# Generated by Django 6.0.3 on 2026-06-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
