# Generated by Django 5.2.13 on 2026-05-07 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_professionalprofile_average_rating_and_more'),
        ('search', '0002_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='search.category'),
        ),
    ]
