# Generated by Django 6.0.3 on 2026-07-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_professionalprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='services',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
