# Generated by Django 6.0.3 on 2026-07-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_professionalprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='response_time_hrs',
            field=models.FloatField(default=24.0),
        ),
    ]
