# Generated by Django 6.0.3 on 2026-07-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_professionalprofile_bank_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='response_time_hrs',
        ),
    ]
