# Generated by Django 6.0.3 on 2026-07-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_search_speed_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='professionalprofile',
            new_name='profiles_pr_hourly__704d2d_idx',
            old_name='prof_hourly_rate_idx',
        ),
        migrations.RenameIndex(
            model_name='professionalprofile',
            new_name='profiles_pr_average_ba47a3_idx',
            old_name='prof_avg_rating_idx',
        ),
    ]
