# Generated by Django 6.0.3 on 2026-07-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_search_speed_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ur', 'Urdu'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish')], max_length=5, null=True),
        ),
    ]
