# Generated by Django 6.0.3 on 2026-07-27 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0009_country_city_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=500)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated.', max_length=500)),
                ('og_image', models.URLField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_seo_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('label', models.CharField(blank=True, help_text="Optional admin note, e.g. 'Added 3 new team members'.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_page_versions_created', to=settings.AUTH_USER_MODEL)),
                ('is_restore_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='about_page.aboutpageversion')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='draft', max_length=15)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_page_publishes', to=settings.AUTH_USER_MODEL)),
                ('current_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='about_page.aboutpageversion')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero_banner', 'Hero Banner'), ('company_story', 'Company Story'), ('mission', 'Mission'), ('vision', 'Vision'), ('why_choose_us', 'Why Choose Us'), ('how_it_works', 'How It Works'), ('statistics', 'Statistics'), ('core_values', 'Core Values'), ('team_members', 'Team Members'), ('investors_partners', 'Investors & Partners'), ('certifications', 'Certifications'), ('awards', 'Awards'), ('contact_info', 'Contact Information'), ('social_media', 'Social Media Links'), ('app_info', 'App Information'), ('legal_links', 'Legal Links'), ('custom', 'Custom Section')], default='custom', help_text='Drives default icon/layout in the admin UI and the app renderer.', max_length=40)),
                ('section_key', models.SlugField(help_text="Stable identifier used by the app to know how to render this section, e.g. 'hero_banner'. Never reused after deletion.", max_length=80, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Rich HTML from the admin rich-text editor (headings, paragraphs, bullet lists, links).')),
                ('icon', models.CharField(blank=True, help_text="Icon key, e.g. 'rocket_launch'.", max_length=100)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
                ('cta_style', models.CharField(choices=[('primary', 'Primary Button'), ('secondary', 'Secondary Button'), ('link', 'Text Link')], default='primary', max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_sections_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_sections_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('link_url', models.CharField(blank=True, help_text='Team member social profile, partner site, certification verification link, etc.', max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='about_page.aboutsection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutSectionItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about_page.aboutsectionitem')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_item_translations', to='admin_panel.language')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_section_translations', to='admin_panel.language')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='about_page.aboutsection')),
            ],
        ),
        migrations.AddIndex(
            model_name='aboutsection',
            index=models.Index(fields=['order'], name='about_section_order_idx'),
        ),
        migrations.AddIndex(
            model_name='aboutsection',
            index=models.Index(fields=['is_enabled'], name='about_section_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='aboutsectionitem',
            index=models.Index(fields=['section', 'order'], name='about_item_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aboutsectionitemtranslation',
            unique_together={('item', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='aboutsectiontranslation',
            unique_together={('section', 'language')},
        ),
    ]
