# Generated by Django 6.0.3 on 2026-07-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_editorial_label_articleview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='color',
            field=models.CharField(default='#2563EB', max_length=7),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='icon',
            field=models.CharField(default='article', max_length=50),
        ),
    ]
