# Generated by Django 5.2.13 on 2026-05-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
