// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYa_FJ35PSIT-nMpJA8B-jObuGB15NJIE',
    appId: '1:299423637189:web:87895f7d9e9a1807931aac',
    messagingSenderId: '299423637189',
    projectId: 'profinder-f3f96',
    authDomain: 'profinder-f3f96.firebaseapp.com',
    storageBucket: 'profinder-f3f96.firebasestorage.app',
    measurementId: 'G-HVKG918K7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs1CAGIhFI-4iyUxTzW-kDMadgTkjckYE',
    appId: '1:299423637189:android:a7f75ef582baac4f931aac',
    messagingSenderId: '299423637189',
    projectId: 'profinder-f3f96',
    storageBucket: 'profinder-f3f96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA4fov7r0tqNOjfy1JqPD5Jm8NfiSCUXo',
    appId: '1:299423637189:ios:4ad1d61288b5c51a931aac',
    messagingSenderId: '299423637189',
    projectId: 'profinder-f3f96',
    storageBucket: 'profinder-f3f96.firebasestorage.app',
    iosBundleId: 'com.example.profinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA4fov7r0tqNOjfy1JqPD5Jm8NfiSCUXo',
    appId: '1:299423637189:ios:4ad1d61288b5c51a931aac',
    messagingSenderId: '299423637189',
    projectId: 'profinder-f3f96',
    storageBucket: 'profinder-f3f96.firebasestorage.app',
    iosBundleId: 'com.example.profinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYa_FJ35PSIT-nMpJA8B-jObuGB15NJIE',
    appId: '1:299423637189:web:7397b291fd916ab6931aac',
    messagingSenderId: '299423637189',
    projectId: 'profinder-f3f96',
    authDomain: 'profinder-f3f96.firebaseapp.com',
    storageBucket: 'profinder-f3f96.firebasestorage.app',
    measurementId: 'G-B189KKTP81',
  );
}
