# Generated by Django 6.0.3 on 2026-06-07 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('verify', 'Verify Professional'), ('ban', 'Ban User'), ('unban', 'Unban User'), ('delete', 'Delete Content'), ('approve', 'Approve Portfolio'), ('reject', 'Reject Portfolio'), ('cancel_booking', 'Cancel Booking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
