# Generated by Django 6.0.3 on 2026-06-27 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_promobanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('verify', 'Verify Professional'), ('ban', 'Ban User'), ('unban', 'Unban User'), ('delete', 'Delete Content'), ('approve', 'Approve Portfolio'), ('reject', 'Reject Portfolio'), ('cancel_booking', 'Cancel Booking'), ('create_banner', 'Create Banner'), ('edit_banner', 'Edit Banner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='priority',
            field=models.IntegerField(default=0, help_text='High = pehle dikhao'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='trigger_x_days',
            field=models.IntegerField(default=3, help_text='trigger=every_x_days hone par: har X din baad show karo'),
        ),
    ]
